# Configuration on how ReadTheDocs (RTD) builds our documentation
# ref: https://readthedocs.org/projects/mybinder/
# ref: https://docs.readthedocs.io/en/stable/config-file/v2.html
#
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

sphinx:
  configuration: doc/conf.py

formats: []

python:
  install:
    - requirements: doc/doc-requirements.txt
