"""
This grabs a few content pages in the repo2docker docs and imports them for use here.

It will put the folders in _data/pages at build time, if they do not currently exist.
"""
import requests
from pathlib import Path

# Grab the latest version of the configuration file examples and howtos
# Files will be placed relative to documentation root
dest_root = Path(__file__).parent.parent.parent
source_root = "https://raw.githubusercontent.com/jupyter/repo2docker/master/docs/source/"
file_mappings = {
    "config_files.rst": "using/config_files.rst",
    "howto/languages.rst": "howto/languages.rst",
    "howto/user_interface.rst": "howto/user_interface.rst",
    "howto/lab_workspaces.rst": "howto/lab_workspaces.rst",

}
for source, dest in file_mappings.items():
  path_dest = dest_root / dest
  if not path_dest.exists():
      print(f"repo2docker page does not exist, downloading from repo2docker docs. {source}")
      url_source = source_root + source
      resp = requests.get(url_source)
      path_dest.parent.mkdir(parents=True, exist_ok=True)
      path_dest.write_text(
          f"""
          .. ##################################################
          .. DO NOT EDIT THIS FILE, IT IS IMPORTED IN `conf.py`
          .. ##################################################

          {resp.text}
          """
      )
  else:
    print(f"repo2docker page exists, skipping download. Delete it to re-download. {source} ")
